name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v5

      - name: Run prek
        uses: j178/prek-action@v1
